apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hello-world-rb
  namespace: hello-world
  annotations:
    argocd.argoproj.io/hook: PreSync
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: hello-world-view-deployments-role
subjects:
- kind: ServiceAccount
  name: default
